# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: moduloMoments
email: rob@modulomoments.com
description: > # this means to ignore newlines until "baseurl:"
  I’m a student of software engineering tackling as many coding experiences as I can in preparation of a new career. I’ll be graduating form Hack Reactor Remote on May 28th, 2016 and I’m always trying to find new ways to learn about the world of coding. This blog is a place where I’ll share a little of my experience in Hack Reactor, using other online resources, and concepts I’m learning in software engineering. Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "rdbruhn.github.io" # the base hostname & protocol for your site
  A software engineering blog by Rob Bruhn
baseurl: "" # the subpath of your site, e.g. /blog
url: "moduloMoments.com" # the base hostname & protocol for your site
twitter_username: robbruhn
github_username:  rdbruhn

# Build settings
markdown: kramdown
